# Generated by Django 3.1.4 on 2020-12-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/courses', verbose_name='Фото'),
        ),
    ]
