# Generated by Django 3.1.4 on 2020-12-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201212_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('vor_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/instuctors', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
