# Generated by Django 3.1.4 on 2020-12-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='estimation',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
