# Generated by Django 3.1.4 on 2020-12-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_courses_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='estimation',
            field=models.IntegerField(),
        ),
    ]
