# Generated by Django 3.1.4 on 2020-12-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201212_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='vor_name',
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.instructors', verbose_name='Преподователь'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='estimation',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя Фамилия'),
        ),
    ]
